models/News.php
<?php

namespace app\models;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class News extends \yii\db\ActiveRecord
{
	/**
	 * @return string
	 */
	public static function tableName()
	{
		return '{{news}}';
	}

	public function behaviors()
	{
		return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => 'create_at',
					ActiveRecord::EVENT_BEFORE_UPDATE => 'modify_at',
				],
				'value' => function () {
					return date('U');
				},
			],
		];
	}

	public function rules()
	{
		return [
			['title', 'required', 'message' => 'Заполните заголовок'],
			['descr', 'required', 'message' => 'Заполните описание'],
			['text', 'required', 'message' => 'Заполните текст'],
			['cat_id', 'integer'],
			['url', 'string'],
			['active', 'safe']
		];
	}

	public function attributeLabels()
	{
		return [
			'title'  => 'Заголовок',
			'descr'  => 'Описание',
			'text'   => 'Текст',
			'cat_id' => 'Категория',
			'active' => 'Активно'
		];
	}

	public function getCategory()
	{
		return $this->hasOne(Categories::className(), ['id' => 'cat_id']);
	}
}

controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Categories;
use app\models\News;
use app\models\News2Cat;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\Inflector;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class AdminController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => 'app\behaviors\AdminBehavior',
			],
		];
	}

    public function actionNewsList()
    {
    	//SELECT news.*, categories.name FROM `news` LEFT JOIN `categories` on (SELECT cat_id from news2cats where news_id = news.id) = categories.id
		//News::find()->orderBy('create_at DESC')
		//$query->select('news.*, categories.name')->from('`news`')->leftJoin('categories', '(SELECT `cat_id` from `news2cats` where `news_id` = `news`.`id`) = `categories`.`id`')->all()
		$query = new Query();
		$dataProvider = new ActiveDataProvider([
			'query' => News::find()->orderBy('create_at DESC'),
			'pagination' => [
				'pageSize' => 10,
			],
		]);

        return $this->render('news-list', ['listDataProvider' => $dataProvider]);
    }

	public function actionAddNew()
	{
		$new = new News();

		if ($new->load(Yii::$app->request->post()))
		{
			$selectedCat = Yii::$app->request->post('cat_id');
			if ($selectedCat == null) {
				$new->cat_id = 0;
			} else {
				$new->cat_id = $selectedCat;
			}
			$new->url = Inflector::slug($new->title, '-');
			$new->save();
			$this->redirect('/admin/news-list');
		}

		return $this->render('add-new', ['model' => $new, 'categories' => Categories::getCatsTreeArray(Categories::find()->all()), 'selectedCats' => []]);
	}

	public function actionEditNew($id)
	{
		if ($id == null) {
			$this->redirect('/admin/news-list');
		}
		$new = News::findOne($id);
		$selectedCats[] = $new->category->id;
		if ($new->load(Yii::$app->request->post()))
		{
			$selectedCat = Yii::$app->request->post('cat_id');
			if ($selectedCat == null) {
				$new->cat_id = 0;
			} else {
				$new->cat_id = $selectedCat;
			}
			$new->url = Inflector::slug($new->title, '-');
			$new->save();
			$this->redirect('/admin/news-list');
		}

		return $this->render('edit-new', ['model' => $new, 'categories' => Categories::getCatsTreeArray(Categories::find()->all()), 'selectedCats' => $selectedCats]);
	}

	public function actionDeleteNew($id)
	{
		if ($id == null) {
			$this->redirect('/admin/news-list');
		}
		$new = News::findOne($id);
		if ($new->delete()) {
			$this->redirect('/admin/news-list');
		}
	}

	public function actionCatsList()
	{
		$dataProvider = new ActiveDataProvider([
			'query' => Categories::find()->orderBy('create_at DESC'),
			'pagination' => [
				'pageSize' => 10,
			],
		]);

		return $this->render('cats-list', ['listDataProvider' => $dataProvider]);
	}

	public function actionAddCat()
	{
		$cat = new Categories();
		if ($cat->load(Yii::$app->request->post()))
		{
			if ($cat->parent_id == null) {
				$cat->parent_id = 0;
			}
			if ($cat->save()) {
				$this->redirect('/admin/cats-list');
			} else {
				$this->redirect('/');
			}
		}

		return $this->render('add-cat', ['model' => $cat]);
	}

	public function actionEditCat($id)
	{
		if ($id == null) {
			$this->redirect('/admin/cats-list');
		}
		$cat = Categories::findOne($id);
		$childs = Categories::find()->select('id')->where(['parent_id' => $id])->asArray()->all();
		if ($cat->load(Yii::$app->request->post()) && $cat->save())
		{
			$this->redirect('/admin/cats-list');
		}

		return $this->render('edit-cat', ['model' => $cat, 'childs' => $childs]);
	}

	public function actionDeleteCat($id)
	{
		if ($id == null) {
			$this->redirect('/admin/cats-list');
		}
		$cat = Categories::findOne($id);
		$news = News::find()->where(['cat_id' => $id])->all();
		foreach ($news as $new) {
			$new->cat_id = 0;
			$new->save();
		}
		if ($cat->delete()) {
			$this->redirect('/admin/cats-list');
		}
	}
}

views/admin/_cats_list_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="item" data-key="<?= $model->id; ?>">
	<h4 class="title">
		#<?= $model->id ?>
        <?= Html::a(Html::encode($model->name), Url::to(['admin/edit-cat', 'id' => $model->id])) . " | " . Html::a('Удалить', Url::to(['admin/delete-cat', 'id' => $model->id])); ?>
	</h4>
    <div><?= date("d.m.Y H:i:s", $model->create_at) ?></div>
	<hr>
</div>

views/admin/_news_list_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="item" data-key="<?= $model->id; ?>">
	<h4 class="title">
		#<?= $model->id ?>
        <?php if (Yii::$app->controller->id == 'admin') {
		    echo Html::a(Html::encode($model->title), Url::to(['admin/edit-new', 'id' => $model->id])) . " | " . Html::a('Удалить', Url::to(['admin/delete-new', 'id' => $model->id]));
        } else {
			echo Html::a(Html::encode($model->title), Url::to(['news/' . $model->url]));
        }
        ?>
	</h4>
    <div>Категория: <?= $model->category->name == null ? 'нет' : $model->category->name ?></div>
    <div><?= date("d.m.Y H:i:s", $model->create_at) ?></div>
	<div class="item-excerpt">
		<?= Html::encode($model->descr); ?>
	</div>
	<hr>
</div>

views/admin/add-cat.php
<?php

use app\models\Categories;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

$this->title = 'Добавить категорию';
$this->params['breadcrumbs'][] = [
	'label' => 'Список категорий',
	'url' => ['/admin/cats-list']
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="body-content">
    <div class="row">
        <div class="col-sm-12">
            <h2><?= $this->title ?></h2>
            <? $form = ActiveForm::begin([
                'id' => 'cats_form',
                'validationStateOn' => 'input',
                'fieldConfig' => [
                    'template' => "<div class=\"form-group\">{label}{input}{error}</div>",
                    'labelOptions' => ['class' => ''],
                ],
                'errorCssClass' => 'is-invalid'
            ]); ?>
            <?= $form->field($model, 'name')->textInput() ?>
			<?= $form->field($model, 'parent_id')->dropdownList(
				Categories::find()->select(['name', 'id'])->indexBy('id')->column(),
				['prompt' => 'Выберите категорию']
			); ?>
            <?php ActiveForm::end(); ?>
			<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' => 'btn btn-primary btn-block', 'form' => 'cats_form']) ?>
        </div>
    </div>
</div>

views/admin/add-new.php
<?php

use app\models\Categories;
use app\models\News;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

$this->title = 'Добавить новость';
$this->params['breadcrumbs'][] = [
	'label' => 'Список новостей',
	'url' => ['/admin/news-list']
];
$this->params['breadcrumbs'][] = $this->title;

$template =
	'<div class="form-group field-advert-active">
        <div class="custom-control custom-checkbox">
            <input type="radio" id="cat_id-{id}" class="custom-control-input" name="cat_id" value="{id}" {checked}>
            <label class="custom-control-label" for="cat_id-{id}">
                <a data-toggle="collapse" href="#multiCollapse_{id}" role="button" aria-expanded="false" aria-controls="multiCollapse_{id}">{name}</a>
                {symbol}
            </label>
        </div>
    </div>';
?>

<div class="body-content">
    <div class="row">
        <div class="col-sm-12">
            <h2><?= $this->title ?></h2>
            <? $form = ActiveForm::begin([
                'id' => 'news_form',
                'validationStateOn' => 'input',
                'fieldConfig' => [
                    'template' => "<div class=\"form-group\">{label}{input}{error}</div>",
                    'labelOptions' => ['class' => ''],
                ],
                'errorCssClass' => 'is-invalid'
            ]); ?>
            <?= $form->field($model, 'title')->textInput() ?>
			<?= $form->field($model, 'descr')->textarea() ?>
			<?= $form->field($model, 'text')->textarea() ?>

            <p>Доступные категории</p>
            <div class="categories-tree">
				<?php echo Categories::buildTree($categories, 0, $template, $selectedCats); ?>
            </div>

            <?= $form->field($model, 'active')->checkbox(['checked ' => true]); ?>
            <?php ActiveForm::end(); ?>
			<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' => 'btn btn-primary btn-block', 'form' => 'news_form']) ?>
        </div>
    </div>
</div>

views/admin/cats-list.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

$this->title = 'Список категорий';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
	<div class="body-content">
		<div class="row">
			<div class="col-sm-12">
				<h2><?= $this->title ?></h2>
				<div><?= Html::a('Добавить категорию', Url::to(['admin/add-cat']), ['class' => 'btn btn-primary']) ?></div>
				<?=
				ListView::widget([
					'dataProvider' => $listDataProvider,
					'summary' => "Показано {begin}-{end} из {totalCount} элемента(ов)",
					'layout' => "{summary}<br>{items}<br>{pager}",
					'itemView' => function ($model, $key, $index, $widget) {
						return $this->render('_cats_list_item',['model' => $model]);
					},
				]);
				?>
			</div>
		</div>
	</div>
</div>

views/admin/edit-cat.php
<?php

use app\models\Categories;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

$this->title = 'Редактирование категории';
$this->params['breadcrumbs'][] = [
	'label' => 'Список категорий',
	'url' => ['/admin/cats-list']
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="body-content">
    <div class="row">
        <div class="col-sm-12">
            <h2><?= $this->title ?></h2>
            <? $form = ActiveForm::begin([
                'id' => 'cats_form',
                'validationStateOn' => 'input',
                'fieldConfig' => [
                    'template' => "<div class=\"form-group\">{label}{input}{error}</div>",
                    'labelOptions' => ['class' => ''],
                ],
                'errorCssClass' => 'is-invalid'
            ]); ?>
            <?= $form->field($model, 'name')->textInput() ?>
			<?= $form->field($model, 'parent_id')->dropdownList(
				Categories::find()->select(['name', 'id'])->where(['not in', 'id', $childs])->andWhere(['!=', 'id', $model->id])->indexBy('id')->column(),
				['prompt' => 'Выберите категорию']
			); ?>
            <?php ActiveForm::end(); ?>
			<?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary btn-block', 'form' => 'cats_form']) ?>
        </div>
    </div>
</div>

views/admin/edit-new.php
<?php

use app\models\Categories;
use app\models\News;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

$this->title = 'Редактирование новости';
$this->params['breadcrumbs'][] = [
	'label' => 'Список новостей',
	'url' => ['/admin/news-list']
];
$this->params['breadcrumbs'][] = $this->title;

$template =
	'<div class="form-group field-advert-active">
        <div class="custom-control custom-checkbox">
            <input type="radio" id="cat_id-{id}" class="custom-control-input" name="cat_id" value="{id}" {checked}>
            <label class="custom-control-label" for="cat_id-{id}">
                <a data-toggle="collapse" href="#multiCollapse_{id}" role="button" aria-expanded="false" aria-controls="multiCollapse_{id}">{name}</a>
                {symbol}
            </label>
        </div>
    </div>';
?>

<div class="body-content">
    <div class="row">
        <div class="col-sm-12">
            <h2><?= $this->title ?></h2>
            <? $form = ActiveForm::begin([
                'id' => 'news_form',
                'validationStateOn' => 'input',
                'fieldConfig' => [
                    'template' => "<div class=\"form-group\">{label}{input}{error}</div>",
                    'labelOptions' => ['class' => ''],
                ],
                'errorCssClass' => 'is-invalid'
            ]); ?>
            <?= $form->field($model, 'title')->textInput() ?>
			<?= $form->field($model, 'descr')->textarea() ?>
			<?= $form->field($model, 'text')->textarea() ?>

            <p>Доступные категории</p>
            <div class="categories-tree">
				<?php echo Categories::buildTree($categories, 0, $template, $selectedCats); ?>
            </div>

            <?= $form->field($model, 'active')->checkbox(); ?>
            <?php ActiveForm::end(); ?>
			<?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary btn-block', 'form' => 'news_form']) ?>
        </div>
    </div>
</div>

views/admin/news-list.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

$this->title = 'Список новостей';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
	<div class="body-content">
		<div class="row">
			<div class="col-sm-12">
				<h2><?= $this->title ?></h2>
				<div><?= Html::a('Добавить новость', Url::to(['admin/add-new']), ['class' => 'btn btn-primary']) ?></div>
				<?=
				ListView::widget([
					'dataProvider' => $listDataProvider,
					'summary' => "Показано {begin}-{end} из {totalCount} элемента(ов)",
					'layout' => "{summary}<br>{items}<br>{pager}",
					'itemView' => function ($model, $key, $index, $widget) {
						return $this->render('_news_list_item',['model' => $model]);
					},
				]);
				?>
			</div>
		</div>
	</div>
</div>